# Cấu hình Theme Minimal Mistakes (Cài đặt qua Gemfile)
theme: "minimal-mistakes-jekyll" 
minimal_mistakes_skin: "default" 

# Cài đặt Cơ bản
title: "HungML's Security Portfolio"
tagline: "DevSecOps | Cloud Security | Threat Hunting"
description: "Nơi chia sẻ các dự án DevSecOps, Threat Hunting và kiến trúc bảo mật."
url: "https://mailoihung.github.io"

# Thông tin Tác giả
author:
  name: "Hưng Mai (Michael)"
  bio: "Security Admin/Engineer. Đam mê DevSecOps và tự động hóa."
  location: "Ho Chi Minh City, Vietnam"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mailoihung"

# Cài đặt Build
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# Ghi đè CSS Mặc định (Đảm bảo chiều rộng tối đa)
defaults:
  # Áp dụng cho tất cả các trang tĩnh (như trang About)
  - scope:
      path: ""
      type: "pages"
    values:
      classes: wide
  # Áp dụng cho tất cả các bài blog (Posts)
  - scope:
      path: ""
      type: "posts"
    values:
      classes: wide

# Cấu hình thanh điều hướng
#main:
#  - title: "Blog Posts"
#    url: /year-archive/
#  - title: "About"
#    url: /about/
